Modal and navigation
PrashanthreddyAinala/DropCss pull request #8
Opened 2022-02-18 01:53 UTC by PrashanthreddyAinala

Added navigation and modal components for component library.

![image](https://user-images.githubusercontent.com/63457391/154602395-c962b750-db2f-4d1b-be37-16faa938d74e.png)

![image](https://user-images.githubusercontent.com/63457391/154602488-9d580512-d0c0-4688-b298-618e3bbead20.png)

2022-02-18 21:45 UTC, muskan-gupta-0803 commented on styles/avatar.css
> +  border-radius: 20px;
avoid using px values.

2022-02-18 21:47 UTC, muskan-gupta-0803 commented on styles/avatar.css
> +  background-color: red;
use your color variables instead of color names here and other places in this file wherever red and white colors are used.

2022-02-18 21:47 UTC, muskan-gupta-0803 commented on styles/avatar.css
> +  background-color: green;
use color variable

2022-02-18 21:56 UTC, muskan-gupta-0803 requested changes
Ui looks good. well done.

You can do the suggested changes. Otherwise all looks fine.
also, later on , you can even create a working preview for your modal, like the opening ang closing of modal using js.

2022-02-19 01:31 UTC, PrashanthreddyAinala commented
@muskan-gupta-0803 Thank you, sure I will work it.

2022-03-05 02:31 UTC, merged